"""add description to writing_sessions

Revision ID: 4df43e1d1da9
Revises: 6289d338b72a
Create Date: 2026-03-24 18:44:47.983243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df43e1d1da9'
down_revision: Union[str, None] = '6289d338b72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_streaks_user_id'), 'streaks', type_='unique')
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=True)
    op.add_column('writing_sessions', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_sessions', 'description')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.create_unique_constraint(op.f('uq_streaks_user_id'), 'streaks', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('messages', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
