"""Add users messages comments streaks writing_sessions tables

Revision ID: 6289d338b72a
Revises: 76be0cd97290
Create Date: 2026-03-24 16:48:11.127543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6289d338b72a'
down_revision: Union[str, None] = '76be0cd97290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First, delete existing data from messages and streaks tables
    # since the schema is changing significantly
    op.execute("DELETE FROM messages")
    op.execute("DELETE FROM streaks")

    # Drop old tables that are being replaced
    op.drop_index(op.f('ix_replies_author'), table_name='replies')
    op.drop_index(op.f('ix_replies_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_message_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_message_id'), table_name='likes')
    op.drop_table('likes')

    # Create users table first (other tables depend on it)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)

    # Create writing_sessions table
    op.create_table('writing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_sessions_id'), 'writing_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_writing_sessions_semester_id'), 'writing_sessions', ['semester_id'], unique=False)
    op.create_index(op.f('ix_writing_sessions_user_id'), 'writing_sessions', ['user_id'], unique=False)

    # Update messages table schema
    # First drop old columns and indexes
    op.drop_index(op.f('ix_messages_author'), table_name='messages')
    op.drop_column('messages', 'department')
    op.drop_column('messages', 'timestamp')
    op.drop_column('messages', 'avatar')
    op.drop_column('messages', 'color')
    op.drop_column('messages', 'author')

    # Create the enum type for category
    op.execute("CREATE TYPE messagecategory AS ENUM ('WIN', 'GAIN')")

    # Add new columns
    op.add_column('messages', sa.Column('category', sa.Enum('WIN', 'GAIN', name='messagecategory'), server_default='WIN', nullable=False))
    op.add_column('messages', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_foreign_key('fk_messages_author_id', 'messages', 'users', ['author_id'], ['id'], ondelete='CASCADE')

    # Create comments table (depends on messages and users)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_message_id'), 'comments', ['message_id'], unique=False)

    # Create message_likes and message_dislikes junction tables
    op.create_table('message_dislikes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.create_table('message_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )

    # Update streaks table - drop old user_id column and recreate with integer type
    op.drop_column('streaks', 'last_updated')
    op.drop_column('streaks', 'user_id')
    op.add_column('streaks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('streaks', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('streaks', sa.Column('last_date', sa.Date(), nullable=True))
    op.add_column('streaks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_streaks_user_id', 'streaks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_streaks_user_id', 'streaks', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete all data since we're reverting to old schema
    op.execute("DELETE FROM streaks")
    op.execute("DELETE FROM messages")

    # Drop junction tables
    op.drop_table('message_likes')
    op.drop_table('message_dislikes')

    # Drop comments table
    op.drop_index(op.f('ix_comments_message_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')

    # Drop writing_sessions table
    op.drop_index(op.f('ix_writing_sessions_user_id'), table_name='writing_sessions')
    op.drop_index(op.f('ix_writing_sessions_semester_id'), table_name='writing_sessions')
    op.drop_index(op.f('ix_writing_sessions_id'), table_name='writing_sessions')
    op.drop_table('writing_sessions')

    # Restore streaks table to old schema
    op.drop_constraint('uq_streaks_user_id', 'streaks', type_='unique')
    op.drop_constraint('fk_streaks_user_id', 'streaks', type_='foreignkey')
    op.drop_column('streaks', 'updated_at')
    op.drop_column('streaks', 'last_date')
    op.drop_column('streaks', 'longest_streak')
    op.drop_column('streaks', 'user_id')
    op.add_column('streaks', sa.Column('user_id', sa.VARCHAR(), nullable=False))
    op.add_column('streaks', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))

    # Restore messages table to old schema
    op.drop_constraint('fk_messages_author_id', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'author_id')
    op.drop_column('messages', 'category')
    op.execute("DROP TYPE messagecategory")
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('messages', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_messages_author'), 'messages', ['author'], unique=False)

    # Drop users table
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Recreate old likes and replies tables
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('likes_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('likes_pkey'))
    )
    op.create_index(op.f('ix_likes_message_id'), 'likes', ['message_id'], unique=False)
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('replies_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('replies_pkey'))
    )
    op.create_index(op.f('ix_replies_message_id'), 'replies', ['message_id'], unique=False)
    op.create_index(op.f('ix_replies_id'), 'replies', ['id'], unique=False)
    op.create_index(op.f('ix_replies_author'), 'replies', ['author'], unique=False)
    # ### end Alembic commands ###
