"""add_current_semester_id_to_users

Revision ID: a3c8652bec2d
Revises: 4df43e1d1da9
Create Date: 2026-03-24 20:12:58.139010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c8652bec2d'
down_revision: Union[str, None] = '4df43e1d1da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_semester_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_current_semester_id'), 'users', ['current_semester_id'], unique=False)
    op.create_foreign_key(None, 'users', 'semesters', ['current_semester_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_current_semester_id'), table_name='users')
    op.drop_column('users', 'current_semester_id')
    # ### end Alembic commands ###
